# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

FROM ubuntu:24.04

#include "$FOLDERBOX_SNIPPETS_DIR/ubuntu"

#include "$FOLDERBOX_SNIPPETS_DIR/ubuntu-dev-cpp"

CMD ["/bin/bash", "--login"]
